services:
  reverse_proxy:
    container_name: reverse_proxy
    build: reverse_proxy/
    networks:
      - reverse_proxy_network
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/apache2:/etc/apache2

  cdn:
    container_name: cdn
    build: cdn/
    networks:
      - reverse_proxy_network
    volumes:
      - ./cdn/nginx/conf/:/etc/nginx

  home:
    container_name: home
    build: home/
    networks:
      - reverse_proxy_network
    volumes:
      - ./home/conf/:/etc/nginx
      - ./home/html/:/usr/share/nginx/html

networks:
  reverse_proxy_network:
    driver: bridge
