# communication between services uses service name not container name
services:
  reverse_proxy:
    container_name: reverse_proxy
    build: reverse_proxy/
    networks:
      - reverse_proxy_network
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/apache2:/etc/apache2

  cdn:
    build: cdn/
    networks:
      - reverse_proxy_network

    deploy:
      mode: replicated
      # if container is down use the other replica
      # replicas are only standby and one of the replicas are used when the used one is down
      replicas: 2

    volumes:
      - ./cdn/nginx/conf/:/etc/nginx

  home:
    build: home/
    networks:
      - reverse_proxy_network
    volumes:
      - ./home/conf/:/etc/nginx
      - ./home/html/:/usr/share/nginx/html

  auth_server:
    container_name: auth_server
    build: auth_server/
    networks:
      - reverse_proxy_network

  streamer:
    container_name: streamer
    build: video_streaming/
    networks:
      - reverse_proxy_network

    volumes:
      - ./video_streaming/conf/:/etc/nginx
      - ./video_streaming/media/:/usr/share/nginx/media

networks:
  reverse_proxy_network:
    driver: bridge
